# Please adjust to your needs (see https://www.gitpod.io/docs/config-gitpod-file)
# and commit this file to your remote git repository to share the goodness with others.

image:
  file: ./gitpod/.gitpod.Dockerfile

tasks:
  - init: |
      pre-commit install \
        && yarn install \
        && yarn run build
    command: yarn run start

# Ports to expose on workspace startup
ports:
  - port: 3000
    onOpen: open-preview
    name: Docusaurus
    description: Docusaurus Preview
