name: Deploy gh pages

on:
  push:
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 15

    - run: |
        npm install
        npm run build
        echo "docs.karnwong.me" > build/CNAME

    - name: Deploy site
      with:
        build-dir: build
        deploy-branch: gh-pages
      uses:  NickSchimek/deploy_jamstack_action@main

    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'

    - name: Index docusaurus
      run: |
        cd docker/docs
        docker run \
          -e APPLICATION_ID=${{ secrets.APPLICATION_ID }} \
          -e API_KEY=${{ secrets.API_KEY }} \
          -e "CONFIG=$(cat algolia-config.json | jq -r tostring)" \
          algolia/docsearch-scraper
