name: Deploy gh pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    ################################
    # Setup node
    ################################
    - name: Setup node
      uses: actions/setup-node@v3.0.0
      with:
        node-version: '16'
        cache: 'yarn'
    - name: Install requirements
      run: yarn install

    ################################
    # Build & deploy
    ################################
    - run: |
        npm run build
        echo "docs.karnwong.me" > build/CNAME

    - name: Deploy site
      with:
        build-dir: build
        deploy-branch: gh-pages
      uses:  NickSchimek/deploy_jamstack_action@main

  create-index:
    runs-on: ubuntu-latest
    needs: build-deploy
    steps:
    - name: Sleep for 5 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '5s'

    - uses: actions/checkout@v3
    - name: Index docusaurus
      run: |
        docker run \
          -e APPLICATION_ID=${{ secrets.APPLICATION_ID }} \
          -e API_KEY=${{ secrets.API_KEY }} \
          -e "CONFIG=$(cat algolia-config.json | jq -r tostring)" \
          algolia/docsearch-scraper
