name: Deploy gh pages

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    ################################
    # Setup node
    ################################
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 15

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-${{ steps.setup-node.outputs.node-version }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
                ${{ runner.os }}-npm

    - name: Install requirements
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
            npm install

    ################################
    # Build & deploy
    ################################
    - run: |
        npm run build
        echo "docs.karnwong.me" > build/CNAME

    - name: Deploy site
      with:
        build-dir: build
        deploy-branch: gh-pages
      uses:  NickSchimek/deploy_jamstack_action@main

  create-index:
    runs-on: ubuntu-latest
    needs: build-deploy
    steps:
    - name: Sleep for 5 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '5s'

    - uses: actions/checkout@v2
    - name: Index docusaurus
      run: |
        docker run \
          -e APPLICATION_ID=${{ secrets.APPLICATION_ID }} \
          -e API_KEY=${{ secrets.API_KEY }} \
          -e "CONFIG=$(cat algolia-config.json | jq -r tostring)" \
          algolia/docsearch-scraper
