name: Deploy

on:
  push:
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # ---------- build ----------
      - name: Setup node
        uses: actions/setup-node@v3.7.0
        with:
          node-version: "18"
          cache: "yarn"
      - name: Install requirements
        run: yarn install
      - name: Build
        run: yarn build
      # ---------- publish ----------
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID}}
          projectName: docs
          directory: .vitepress/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  create-index:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Sleep for 5 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: "5s"

      - uses: actions/checkout@v3
      - name: Index docusaurus
        run: |
          docker run \
            -e APPLICATION_ID=${{ secrets.ALGOLIA_APPLICATION_ID }} \
            -e API_KEY=${{ secrets.ALGOLIA_API_KEY }} \
            -e "CONFIG=$(cat algolia-config.json | jq -r tostring)" \
            algolia/docsearch-scraper
